server:
  port: 8081
spring:
  application:
    name: hotel-api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: guest-service
          uri: lb://GUEST-SERVICE
          #          uri: http://localhost:8082
          predicates:
            - Path=/api/guest/**
          filters:
          #           - CustomFilter1

        - id: hotel-service
          uri: lb://HOTEL-SERVICE
          #          uri: http://localhost:8083
          predicates:
            - Path=/api/hotel/**
          filters:
        #            - CustomFilter1

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          #          uri: http://localhost:8084
          predicates:
            - Path=/api/reservation/**
          filters:
        #            - CustomFilter1

        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          #          uri: http://localhost:8085
          predicates:
            - Path=/api/authentication/**
          filters:
            - CustomFilter1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost