server:
  port: 0
spring:
  application:
    name: reservation-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: password
    flyway:
      schemas: reservation
      user: postgres
      password: password
      enabled: true
  cloud:
    bootstrap:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

internal-api:
  hotel-service:
    name: hotel-service
    path: /api/hotel

resilience4j:
  circuitbreaker:
    instances:
      circuit_1:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
